encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("random", views.random, name="random"),
    path("newentry", views.newentry, name="newentry"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("<str:title>", views.wikientry, name="wikientry")

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
from django import forms
from random import randint
from os import path
from django.urls import reverse
from django.http import HttpResponseRedirect

from . import util


class NewSearchForm(forms.Form):
    searchQuery = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia',
                                                                          'class': 'search'}))


class NewEntryForm(forms.Form):
    title = forms.CharField(label="", widget=forms.TextInput(
        attrs={'placeholder': 'Enter title of new wiki entry here...', 'class': 'search'}))
    entryForm = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter a new wiki entry here...',
                                                             'class': 'search'}), label="")


class EditEntryForm(forms.Form):

    old_entry_form = forms.CharField(widget=forms.Textarea(attrs={'class': 'search'}), label="")


def index(request):
    if request.method == "POST":

        form = NewSearchForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():
            # Isolate the searchquery from the 'cleaned' version of form data
            searchquery = form.cleaned_data["searchQuery"]

            # Define variables bool_entryfound and array_string_searchresults from search method
            bool_entryfound, array_string_searchresults = util.search(searchquery)
            # Redirect user to list of tasks
            if bool_entryfound:
                print(f"Found one entry for searchquery {searchquery}")
                return wikientry(request, array_string_searchresults[0])
            elif not bool_entryfound and len(array_string_searchresults) == 0:
                print(f"Found no entries for searchquery {searchquery}")
                return wikientry(request, searchquery)
            else:
                print(f"Found {len(array_string_searchresults)} entries for searchquery {searchquery}")
                return render(request, "encyclopedia/index.html", {
                    "entries": array_string_searchresults,
                    "form": NewSearchForm()
                })

    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "form": NewSearchForm()
        })


def wikientry(request, title):
    print(f"Searching for title: {title}")
    markdowner = Markdown()
    wiki_entry = util.get_entry(title)
    if wiki_entry is None:
        return render(request, "encyclopedia/entrymissing.html", {
            "title": title,
            "form": NewSearchForm()
        })
    else:
        return render(request, "encyclopedia/wikientry.html", {
            "entryAsHTML": markdowner.convert(wiki_entry),
            "title": title,
            "form": NewSearchForm()
        })


def random(request):
    """
    Returns a random wiki entry
    :return: HttpResponseRedirect
    """
    print("Searching for random wiki entry")
    list_string_allentries = util.list_entries()
    int_random = randint(0, len(list_string_allentries) - 1)
    print(f"Entry {list_string_allentries[int_random]} was chosen. Navigating to wiki entry page.")
    return HttpResponseRedirect(reverse("encyclopedia:wikientry",
                                        args=(path.splitext(list_string_allentries[int_random])[0],)))


def newentry(request):
    if request.method == "POST":

        new_entry_form: NewEntryForm = NewEntryForm(request.POST)

        str_new_entry_title: str
        str_new_entry_data: str

        # Check if form data is valid (server-side)
        if new_entry_form.is_valid():
            str_new_entry_title, str_new_entry_data = new_entry_form.cleaned_data["title"], \
                                                      new_entry_form.cleaned_data["entryForm"]

            if util.search(str_new_entry_title)[0]:
                return render(request, "encyclopedia/newentry.html", {
                    "form": NewSearchForm,
                    "entry": new_entry_form,
                    "warning": True
                })
            else:
                f = open(f"entries/{str_new_entry_title}.md", "w+")
                f.write(str_new_entry_data)
                f.close()
                return HttpResponseRedirect(str_new_entry_title)
    else:
        return render(request, "encyclopedia/newentry.html", {
            "form": NewSearchForm(),
            "entry": NewEntryForm()
        })


def edit(request, title):
    if request.method == "GET":
        return render(request, "encyclopedia/editentry.html", {
            "form": NewSearchForm(),
            "entry": EditEntryForm(initial={"old_entry_form": util.get_entry(title)}),
            "title": title
        })
    elif request.method == "POST":

        edited_entry: EditEntryForm = EditEntryForm(request.POST)

        str_new_entry_data: str

        # Check if form data is valid (server-side)
        if edited_entry.is_valid():
            str_new_entry_data = edited_entry.cleaned_data["old_entry_form"]

            f = open(f"entries/{title}.md", "w+")
            f.write(str_new_entry_data)
            f.close()
            return HttpResponseRedirect(reverse("encyclopedia:wikientry", args=(title,)))

encyclopedia/templates/encyclopedia/editentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:edit' title%}" method="post">
        {% csrf_token %}
        {{ entry }}
        <input type="submit" value="Save changes">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entrymissing.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Entry does not exist
{% endblock %}

{% block body %}
<p>We are sorry, the entry for <strong>{{ title }}</strong> does not exist.</p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% empty %}
            <li>No entries for your search.</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>

                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                     <a href="{% url 'encyclopedia:newentry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:newentry' %}" method="post">
        {% csrf_token %}
        {% if warning %}
         <div class="alert">
              <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
              Warning. This entry already exists.
        </div>
        {% endif %}
        {{ entry }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/wikientry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
{{ entryAsHTML|safe }}

{% endblock %}